### ISSUE TITLE
Vextrex `.ovr` files are included as part of the index

### ISSUE THREAD

**Issue by RGarciaLago** [wizzomafizzo/mrext#12]
Title explains it. The `.ovr` files in the Vectrex games folder are treated like separate game entries.

**Comment by wizzomafizzo** [comment]
Thank you! I've just commented them out for now. Might be some others like that in there when I was mindlessly copying over the conf strings of all the cores

Interesting thing is I think it would be possible to generate an mgl with a game and overlay. But I don't know how you could tell automatically which is the right overlay (or if anyone would even care since it's vectrex)
